parameters:
#    custom_cms.example.class: Custom\CMSBundle\Example

services:
#    custom_cms.example:
#        class: %custom_cms.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
